# Site settings
name: Dev&Ops gwoose's Blog
email: gwoose@126.com
author: gwoose
url: https://gwoose.github.io
resume_site: https://gwoose.github.io/Resume.html
github: https://github.com/gwoose/
baseurl: ""
description: Actually, less is more!
meta_description: gwoose;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

gems: [jekyll-paginate]
github_username: gwoose 
highlighter: Pygments

# Build settings
markdown: kramdown

FB:
  comments :
    provider : gwoose
    duoshuo:
        short_name : gw
    disqus :
        short_name : GW
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light
